apiVersion: v1
kind: Service
metadata:
  name: churnops-inference
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: churnops-inference
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
