apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: churnops-inference
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: churnops-inference
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 5s
