apiVersion: apps/v1
kind: Deployment
metadata:
  name: churnops-inference
spec:
  template:
    spec:
      containers:
        - name: inference-api
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: "1"
              memory: 1Gi
